# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Materials Data Mining with Python"
author: Valentina Miranda
logo: logo_fr.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/vmiranda4/materials-data-mining  # Online location of your book
  branch: main
  path_to_book: tutorial


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_download_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  thebe: true


